### ISSUE TITLE
Errors when editing quickfix buffer when filetype_is_not set to "qf"

### ISSUE THREAD

**Issue by jdsutherland** [Pocco81/AutoSave.nvim#1]
I use https://github.com/stefandtw/quickfix-reflector.vim, which allows editing the quickfix buffer to write changes. Autosave will make a mess of this, so I attempted to disable:

```lua
require("autosave").setup({
  verbosity = 0,
  enabled = true,
  events = {"InsertLeave", "TextChanged"},
  conditions = {
      exists = true,
      filetype_is_not = {"qf"}, -- <===
      modifiable = true
  },
  write_all_buffers = true,
  on_off_commands = true,
})
```

But I get errors when I edit the quickfix buffer:
```
Error detected while processing TextChanged Autocommands for "*":
E5108: Error executing lua .../plugged/AutoSave.nvim/lua/autosave/modules/autocmds.lua:93: Vim(buffer):E86: Buffer 267 does not exist
```

**Comment by Pocco81** [comment]
For now set `write_all_buffers = false`. I'm working on a fix right now. The problem has nothing to do with `filetype_is_not = {"qf"}` btw.

**Comment by jdsutherland** [comment]
Ok. Before changing `write_all_buffers = false`, I'm pretty sure the same error occurred when interacting with vim-fugitive `:G` buffers. I assume this stems from the same issue.
