### ISSUE TITLE
Autosave.nvim makes my undotree dirty

### ISSUE THREAD

**Issue by Lakshamana** [Pocco81/AutoSave.nvim#10]
Hello, there. Awesome plugin!

The issue I'm bringing here is that somehow whenever I type `u` to undo on Neovim (specs on below image) the expected previous edit does not appear. Instead it blinks the [+] on the low bar like a new edition was being made and then when I check my undotree it is full of empty edition entries, check it out:
This is my nvim configuration:
![image](https://user-images.githubusercontent.com/29443505/133637865-9e0caac0-dc66-46e8-88cb-238b0149ca72.png)

This is the undotree:
![image](https://user-images.githubusercontent.com/29443505/133638853-48fd233d-5404-49f8-8d0d-1431c5ff5fd0.png)

Pointing it to one of edits entry (please notice, timestamps would change due to time I'm taking shots and editing this issue as well)
![image](https://user-images.githubusercontent.com/29443505/133636026-48fcdc72-83e1-4df4-984c-0ffb9f4f8aa9.png)

Immediately previous edit entry:
![image](https://user-images.githubusercontent.com/29443505/133636222-2c8746ab-4405-4039-af5d-0dc8feb6c675.png)

As you see this is what I called empty edit entries.

Now, this is my basic conf to reproduce such error (init.vim):
```
local autosave = require("autosave")

autosave.setup(
    {
        enabled = true,
        -- execution_message = "AutoSave: saved at " .. vim.fn.strftime("%H:%M:%S"),
        execution_message = "",
        events = {"TextChanged", "InsertLeave"},
        conditions = {
            exists = true,
            filetype_is_not = {},
            modifiable = true
        },
        write_all_buffers = false,
        on_off_commands = true,
        clean_command_line_interval = 0,
        debounce_delay = 135
    }
)
EOF
```

Please notice, I tested with this plugin enabled and disabled and got not issues at all by running `u` with this plugin disabled. This would let me conclude the issue is with autosave.nvim. So the basic outcome of this issue is that it takes a lot of `u` tapping to get me the real previous editing.

Thank you!

EDIT: I don't know if this helps you but, leaving just "InsertLeave" the entry `events` seems to "resolve" the issue, albeit it will not save changes made on Normal Mode.

**Comment by Pocco81** [comment]
Hey! As weird as this may sound, this is expected behavior. As you said, leaving only the `InsertEnter` event works well, that's because the culprit is `TextChanged`.

There is actually a warning about it in vim's doc:

> Careful: This is triggered very often, don't                                                                do anything that the user does not expect or                                                                that is slow.

I too get this issue, but the issue is not the plug-in itself. Like you could just write a very simple one-line autocommand to save on `TextChanged` and you'll see the same behavior.

Sandly this is so _random_ that it's hard to reproduce....

**Comment by Lakshamana** [comment]
@Pocco81, the current config for your own plugin is exactly the same as the docs? Thank you for your fast response here, btw

**Comment by Pocco81** [comment]
> I wouldn't notice nothing wrong in the past few days, then suddenly things stop working the way it should be =\

As I said, this is very very random. But regardless of its nature it should only cause errors the buffer is saved while some other plugin needs to do some stuff with the unmodified buffer. This is actually the reason for the `debounce_delay` setting.

I actually remember having an problem with an autocompletion plugin (don't remember if it was that) that needed to read the unsaved buffer, so varying the delay worked.

Feel free to play around with both the `events` and the `debounce_delay` settings!

If it helps, here are some issues regarding undoing stuff when using an auto save type-of plugin:
+ https://github.com/907th/vim-auto-save/issues/37
+ https://github.com/907th/vim-auto-save/issues/53
+ https://github.com/907th/vim-auto-save/issues/51
+ https://github.com/907th/vim-auto-save/issues/41
