### ISSUE TITLE
[Question] Retrieve current status

### ISSUE THREAD

**Issue by lcrockett** [Pocco81/AutoSave.nvim#18]
Cheers on the excellent plugin, works great for me. I was just wondering if it's possible to retrieve the current status (on or off) of the plugin somehow. This way I could integrate the status in (for example) the statusline to determine it's current status and based on that toggle it, or not. This prevents me from having to have to use the explicit on / off commands.

I found a `get_status` function in `lua/autosave/main.lua`, but that doesn't seem to be exposed outside of the plugin and i'm not too familiar with (Neovim) Lua to understand if I can read out 'made-up' `M` table contents. Any pointers perhaps ?

**Comment by Pocco81** [comment]
Good idea, I'll expose it.

**Comment by Pocco81** [comment]
[Cheers](https://github.com/Pocco81/AutoSave.nvim#general)

**Comment by lcrockett** [comment]
Fantastic, tested and works well, thanks !
