### ISSUE TITLE
Feature request: disable message 

### ISSUE THREAD

**Issue by rounakcodes** [Pocco81/AutoSave.nvim#29]
Is there a way to disable the "AutoSave: saved at ..." message? It hides the previous message from the status bar which may be important. 
I (and hopefully most of us) can always check for the presence of 'unsaved' marker at the top of my tab/window near the filename to know whether the current edits have been saved.

**Comment by danserk** [comment]
execution_message = "" works just fine for me

**Comment by rounakcodes** [comment]
Thanks. It works. I may have made a mistake when I tried it before posting here.

**Comment by rounakcodes** [comment]
Can someone confirm if this still works? I updated the plugin today and it did not change my config. It seems to not work.

**Comment by LintaoAmons** [comment]
> Can someone confirm if this still works? I updated the plugin today and it did not change my config. It seems to not work.

Just delete the whole thing after the `after_saving` callback

<img width="1537" alt="image" src="https://user-images.githubusercontent.com/95092244/215131432-dc571c8f-9b2d-49b1-9505-359a0221fba2.png">

**Comment by biozz** [comment]
The format has changed a bit:

```lua
require("auto-save").setup({
        ...
	execution_message = {
		message = function()
			return ""
		end,
		dim = 0.18,
		cleaning_interval = 1250,
	},
	...
})
```

You still have to add dim and cleaning interval, which is a minor annoyance, but it works.
