### ISSUE TITLE
Only first window has filetype set when launching nvim with splits

### ISSUE THREAD

**Issue by jdsutherland** [Pocco81/AutoSave.nvim#3]
Reproducible using AutoSave.nvim default config.

Steps
1. `nvim -O file1 file2 file3` (either -o or -O)
2. Only the first window has syntax highlighting (filetype not set for others)

**Comment by jdsutherland** [comment]
Sorry, I'd forgot I had https://github.com/Pocco81/AutoSave.nvim/tree/dev checked out. The issue isn't on master. Hopefully this helps though.

**Comment by Pocco81** [comment]
Please don't use the dev branch yet! I was working on it yesterday but left it incomplete! I'll update you as soon as it's ready.
