### ISSUE TITLE
Disable output

### ISSUE THREAD

**Issue by jdsutherland** [Pocco81/AutoSave.nvim#4]
The readme mentions `verbosity` but it doesn't seem to be implemented. I'd like to disable the output logging save times. I find it noisy and unnecessary.

**Comment by jdsutherland** [comment]
It looks like setting `execution_message = ""` does this. Maybe this could be a little more clear in the readme?

**Comment by Pocco81** [comment]
The verbosity thing was because I used the README from another plug-in as a template, and well I guess I accidentally left that there! My bad, I'll fix the README as soon as possible.
