### ISSUE TITLE
breaks selecting previous text

### ISSUE THREAD

**Issue by jdsutherland** [Pocco81/AutoSave.nvim#5]
https://stackoverflow.com/questions/4312664/is-there-a-vim-command-to-select-pasted-text

When AutoSave.nvim is enabled, this doesn't work. Instead of selecting the previous text, the entire file is selected.

**Comment by jdsutherland** [comment]
Sorry, it's not the plugin itself. It looks like this occurs when you have an an autocmd for `TextChanged`.

**Comment by Pocco81** [comment]
TextChanged is a very volatile event, even the wiki says to use it carefully:

> Careful: This is triggered very often, don't do anything that the user does not expect or that is slow.

This and other events like CursorMove get executed very very often. Maybe I should consider disabling it by default.

Thanks I'll consider this!

**Comment by jdsutherland** [comment]
Sometimes I want to use `TextChanged`, as it's useful when using livereload to see browser changes in real time without having to manually save (if the change doesn't involve insert mode). I'm thinking I'd like to create a command or map to toggle it on. How would you recommend doing this? AFAIK, the only way to set it is:
`require("autosave").setup({ events = {"InsertLeave", "FocusLost", "TextChanged"}})`

I'm not sure if it's possible to query the value of events after calling `setup` or if it's possible to just update just the `events` key (without affecting the rest of the options). I suspect not, but I don't know lua very well.

**Comment by Pocco81** [comment]
You can use:

```lua
execute "lua require'autosave.modules.autocmds'.save()"
```

And then use the api to map and assert the autocommand autocommand:
```
local cmd = vim.cmd

local function load_my_save()
    cmd(
        [[
			aug autosave_custom_save
				au!
				au TextChanged * execute "lua require'autosave.modules.autocmds'.save()"
			aug END
	]]
    )
end

local function unload_my_save()
    cmd(
        [[
			aug autosave_custom_save
				au!
			aug END
	]]
    )
end

vim.api.nvim_set_keymap("n", "<C-s>", [[if !exists('g:custom_save') | execute "lua load_my_save()" | let g:custom_save = 1 | else | execute "lua unload_my_save()" | unlet g:custom_save | endif]], {noremap = true, silent = true})
``

**Comment by jdsutherland** [comment]
Hmm, I'm getting `No mapping found`.

**Comment by jdsutherland** [comment]
When I hit the map, it inserts: `f !exists('g:custom_save') | execute "lua load_my_save()" | let g:custom_save = 1 | else | execute "lua unload_my_save()" | unlet g:custom_save | endif`, which makes me think the initial `i` is putting it in insert mode and inserting the rest.

**Comment by Pocco81** [comment]
I haven't tried it, I just made it for you. But I guess that happened because if the opts in the key map func. Just change them or pass an empty table and you should be good to go.
