### ISSUE TITLE
`condition` not working for "sql" files

### ISSUE THREAD

**Issue by gegnew** [Pocco81/AutoSave.nvim#75]
Despite #39 and the docs, I can't seem to prevent `auto-save` from saving when I'm in a `.sql` file. Specifically, I'm using [DBUI](https://github.com/kristijanhusak/vim-dadbod-ui), which runs queries on file save, and I'd _really_ like to not run a large query every time I change any text.

- The buffer name while in DBUI is i.e. `/tmp/nvim.g/EyVbLv/eegdb-EEG-List-2023-03-31-10-26-41`.
- There are three panes in DBUI, of file time "sql", "dbout", and "dbui". Only the "sql" file _should_ be relevant, since it's saving this file that triggers the query.
- While in the "sql" file, running `lua print(require("auto-save.utils.data").not_in(vim.fn.getbufvar(1, "&filetype"), {"sql"}))` prints nothing (i.e. "false"), as expected

My config:

```lua
return function()
    require("auto-save").setup({
        enabled = false,
        condition = function(buf)
            local fn = vim.fn
            local utils = require("auto-save.utils.data")

            if fn.getbufvar(buf, "&modifiable") == 1
                and utils.not_in(fn.getbufvar(buf, "&filetype"), {
                    "sql",
                    "dbout",
                    "dbui",
                })
            then
                return true -- met condition(s), can save
            end
            return false -- can't save
        end,
        write_all_buffers = false,
    })
end

````

**Comment by primeapple** [comment]
Try the following function for `condition`:
```
 		function(buf)
                local fn = vim.fn
                local utils = require("auto-save.utils.data")

            if fn.getbufvar(buf, "&modifiable") == 1
                and utils.not_in(fn.getbufvar(buf, "&filetype"), {
                    "sql",
                    "dbout",
                    "dbui",
                })
            then
                print('not in sql file')
                return true -- met condition(s), can save
            end
            print('in sql file')
            return false -- can't save
        end
```

I tested it in the better maintained fork: https://github.com/okuuva/auto-save.nvim and it worked fine for me.

**Comment by gegnew** [comment]
fiddled with things again, changed to the `okuuva` repo; seem to have managed to get it to work. Thanks!
