### ISSUE TITLE
how can i disable notification?

### ISSUE THREAD

**Issue by semi710** [Pocco81/AutoSave.nvim#82]
as i use notify nvim it is quite annoying getting notified every time i switch to normal mode and the buffer is saved

**Comment by okuuva** [comment]
@niksingh710 there's a bug that causes configuration options to not work properly, see #76. You could try out the maintained fork where it and plenty of other bugs have been fixed, and some new cool features (like deferred save discussed in #72) have been implemented: https://github.com/okuuva/auto-save.nvim.

I guess it's obvious but still, full disclosure: I'm one of the maintainers of the said fork.

**Comment by semi710** [comment]
> @niksingh710 there's a bug that causes configuration options to not work properly, see #76. You could try out the maintained fork where it and plenty of other bugs have been fixed, and some new cool features (like deferred save discussed in #72) have been implemented: [okuuva/auto-save.nvim](https://github.com/okuuva/auto-save.nvim).
> 
> I guess it's obvious but still, full disclosure: I'm one of the maintainers of the said fork.

ty mate wasn't aware of the fork.
With the fork it is working as expected.
