### ISSUE TITLE
AutoSave turning on after every restart of Neovim

### ISSUE THREAD

**Issue by reactVishnu** [Pocco81/AutoSave.nvim#86]
Hi,

Whenever am quiting and start neovim again the auto save gets automatically onn for no reason..

For eg: If i toggle off the autosave while working in some directory and if i quit and again opens it , The autosave automatically turns on at the time of starting.User need to again toggle it off.

**Comment by primeapple** [comment]
If you could post your config that would help. Also you may want to have a look if it happens with the more maintained fork: https://github.com/okuuva/auto-save.nvim (Disclaimer, I'm one of the maintainers)

**Comment by reactVishnu** [comment]
My conifg for this plugin.
```
return {
  "pocco81/auto-save.nvim",
  event = { "VeryLazy" },
}
```
 Let me know if am missing something ... Am using NVchad distro which uses lazy package manager.

If you need to look at my whole config, it is present [there.](https://github.com/reactVishnu/Neovim-Config-Pycharm-)
And i will try okuuva/autosave.nvim  and will let u know if it's able to resolve.

**Comment by reactVishnu** [comment]
Hi, 
I tried okuuva/autosave.nvim and it's still the same.

**Comment by primeapple** [comment]
Please post an issue [there](https://github.com/okuuva/auto-save.nvim/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc). Since nvChad uses Lazy it surely has a lazy-lock.json file. That has to be posted as well.

If you want autosave to be disabled at start and only be enabled when you toggle it, try to set it up with `require("auto-save").setup({enabled = false})`

**Comment by reactVishnu** [comment]
Hi,

The one you gave fixed for me. My final config look like this.

```
return {
  "okuuva/auto-save.nvim",
  cmd = "ASToggle", -- optional for lazy loading on command
  event = { "InsertLeave", "TextChanged" }, -- optional for lazy loading on trigger events
  opts = {
    -- your config goes here
    -- or just leave it empty :)
  },
  keys = {
    { "<leader>sa", ":ASToggle<CR>", desc = "Toggle auto-save" },
  },
  config = function()
    require("auto-save").setup { enabled = false }
  end,
}
```
Closing the issue.
