### ISSUE TITLE
Warning Messages on NeoVim Load up

### ISSUE THREAD

**Issue by centuryx476** [Pocco81/AutoSave.nvim#93]
Hello,
I went thru the closed issues and sorta found related issues but none of them can resolve this pop up happening in NeoVim.
Any work around ?

![image](https://github.com/user-attachments/assets/4d45836c-39b5-4348-ba68-0674469cf223)

**Comment by centuryx476** [comment]
Ok, I am an idiot. 
Updated the autosave.lua in my LazyVim

Fixed it

Thank You

**Comment by primeapple** [comment]
Yes, for anyone stumbling about this: it is from the fork https://github.com/okuuva/auto-save.nvim
